### ISSUE TITLE
Upgrades picking

### ISSUE THREAD

**Issue by prietzem** [prietzem/spacerex#102]
More Upgrades should be able to select at the same time and stackable

**Comment by GuncraftaM1P** [comment]
i think it's fixed now, i noticed a few things tho:
- does owned upgrades really have to be a sorted list? -> can remove allot of code otherwise
- don't refresh all upgrades' positions in manage player all the time, just add the new upgrade at a random position if removing it from the equipped list
- draw the upgrades in UpgradeBox backwards, so new Upgrades get added from the right, not the left
- remove the numbers before finishing the issue -> add another indicator for how many of the same item u have
